import { motion } from 'framer-motion';

export function LegalPage({ title = "Legal Policy" }: { title?: string }) {
  return (
    <div className="pt-48 pb-24 px-6 max-w-[1200px] mx-auto min-h-[70vh]">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="glass-card p-12 md:p-20 border-white/5 bg-dark/[0.5] relative overflow-hidden"
      >
        <div className="absolute top-0 right-0 w-[400px] h-[400px] bg-emerald/5 rounded-full blur-[120px] pointer-events-none -z-10"></div>
        
        <div className="inline-flex items-center text-xs font-bold uppercase tracking-widest text-emerald bg-emerald/10 px-4 py-1.5 rounded-full border border-emerald/20 mb-8">
          OFFICIAL DOCUMENTATION
        </div>

        <h1 className="text-4xl md:text-6xl font-black text-white uppercase tracking-tighter mb-10">{title}</h1>
        
        <div className="prose prose-invert prose-emerald max-w-none text-gray-400 font-medium leading-relaxed">
          <p className="text-xl text-gray-300 leading-relaxed max-w-3xl mb-12">
            Please note that our policies are currently being reviewed and updated for the 2026 fiscal year compliant with automated algorithmic trading regulations. This is a placeholder document.
          </p>
          
          <h2 className="text-white text-2xl font-black uppercase mt-12 mb-6 tracking-tight">Standard Disclosures</h2>
          <p className="mb-8">
            InvestAI provides automated research tools but does not offer direct financial advice. All data and insights generated by the system should be verified against primary sources like SEC EDGAR filings and Bloomberg Terminals. Investments in digital assets and algorithmic strategies carry inherent risks and volatility.
          </p>

          <h2 className="text-white text-2xl font-black uppercase mt-12 mb-6 tracking-tight flex items-center gap-3">
             <span className="w-2 h-2 rounded-full bg-emerald"></span> Data & Privacy Standard
          </h2>
          <p className="mb-10">
            For users of the RAG engine and Chat widgets, we employ local quantization and SOC-2 standard encryption for all prompt data. Institutional users are provided dedicated isolated instances on Cloudflare workers to ensure strategy confidentiality.
          </p>

          <div className="h-px w-full bg-white/5 my-12"></div>

          <p className="text-sm font-bold tracking-widest uppercase opacity-60">
            If you have any urgent inquiries regarding our proprietary financial models, automated execution systems, or enterprise integrations, please reach out directly: legal@investai.pro
          </p>
        </div>
      </motion.div>
    </div>
  );
}
